// Package classifier determines the category of a file based on
// its path and extension.
package classifier

import (
	"path/filepath"
	"strings"

	"github.com/arpan/ctxguard/internal/report"
)

// Classify returns the FileCategory for a given relative file path.
func Classify(relPath string) report.FileCategory {
	relPath = filepath.ToSlash(relPath)
	lower := strings.ToLower(relPath)
	base := strings.ToLower(filepath.Base(relPath))
	ext := strings.ToLower(filepath.Ext(relPath))

	// Vendor detection (path-based, checked first).
	if isVendor(lower) {
		return report.CategoryVendor
	}

	// Generated file detection.
	if isGenerated(lower, base) {
		return report.CategoryGenerated
	}

	// Test file detection.
	if isTest(lower, base) {
		return report.CategoryTest
	}

	// Documentation.
	if isDocumentation(lower, base, ext) {
		return report.CategoryDocumentation
	}

	// Config files.
	if isConfig(base, ext) {
		return report.CategoryConfig
	}

	// Data files.
	if isData(ext) {
		return report.CategoryData
	}

	// Code files.
	if isCode(ext) {
		return report.CategoryCode
	}

	return report.CategoryOther
}

func isVendor(lower string) bool {
	prefixes := []string{
		"vendor/", "node_modules/", "third_party/", "third-party/",
		"external/", "deps/",
	}
	for _, p := range prefixes {
		if strings.HasPrefix(lower, p) || strings.Contains(lower, "/"+p) {
			return true
		}
	}
	return false
}

func isGenerated(lower, base string) bool {
	// Common generated file indicators.
	indicators := []string{
		"generated", "auto_generated", "autogenerated",
		".gen.", ".pb.", ".pb.go", "_generated",
	}
	for _, ind := range indicators {
		if strings.Contains(lower, ind) {
			return true
		}
	}
	// Lock files are generated.
	generatedFiles := []string{
		"package-lock.json", "yarn.lock", "go.sum",
		"poetry.lock", "cargo.lock", "gemfile.lock",
		"pnpm-lock.yaml", "composer.lock",
	}
	for _, gf := range generatedFiles {
		if base == gf {
			return true
		}
	}
	return false
}

func isTest(lower, base string) bool {
	// Test directories.
	testDirs := []string{
		"test/", "tests/", "spec/", "specs/",
		"__tests__/", "__test__/", "testdata/",
	}
	for _, td := range testDirs {
		if strings.HasPrefix(lower, td) || strings.Contains(lower, "/"+td) {
			return true
		}
	}
	// Test file naming conventions.
	testPatterns := []string{
		"_test.go", "_test.py", "_test.js", "_test.ts",
		".test.js", ".test.ts", ".test.tsx", ".test.jsx",
		".spec.js", ".spec.ts", ".spec.tsx", ".spec.jsx",
		"_spec.rb",
	}
	for _, tp := range testPatterns {
		if strings.HasSuffix(lower, tp) {
			return true
		}
	}
	return false
}

func isDocumentation(lower, base, ext string) bool {
	if ext == ".md" || ext == ".rst" || ext == ".txt" || ext == ".adoc" {
		return true
	}
	docDirs := []string{"docs/", "doc/", "documentation/"}
	for _, dd := range docDirs {
		if strings.HasPrefix(lower, dd) || strings.Contains(lower, "/"+dd) {
			return true
		}
	}
	docFiles := []string{
		"readme", "changelog", "changes", "history",
		"contributing", "license", "licence", "authors",
		"code_of_conduct", "security",
	}
	baseName := strings.TrimSuffix(base, ext)
	for _, df := range docFiles {
		if baseName == df {
			return true
		}
	}
	return false
}

func isConfig(base, ext string) bool {
	configExts := map[string]bool{
		".yaml": true, ".yml": true, ".toml": true, ".ini": true,
		".cfg": true, ".conf": true, ".env": true, ".properties": true,
	}
	if configExts[ext] {
		return true
	}
	configFiles := map[string]bool{
		"makefile": true, "dockerfile": true, "docker-compose.yml": true,
		".editorconfig": true, ".eslintrc": true, ".prettierrc": true,
		".gitignore": true, ".gitattributes": true, ".ctxignore": true,
		"go.mod": true, "go.sum": true, "package.json": true,
		"tsconfig.json": true, "pyproject.toml": true, "setup.py": true,
		"setup.cfg": true, "cargo.toml": true, "gemfile": true,
		".babelrc": true, ".browserslistrc": true,
		"jest.config.js": true, "webpack.config.js": true,
		"vite.config.js": true, "vite.config.ts": true,
	}
	// go.sum is already handled as generated; config detection happens after.
	return configFiles[base]
}

func isData(ext string) bool {
	dataExts := map[string]bool{
		".json": true, ".xml": true, ".csv": true, ".tsv": true,
		".sql": true, ".sqlite": true, ".db": true,
		".parquet": true, ".avro": true, ".ndjson": true,
	}
	return dataExts[ext]
}

func isCode(ext string) bool {
	codeExts := map[string]bool{
		// Go
		".go": true,
		// JavaScript/TypeScript
		".js": true, ".ts": true, ".jsx": true, ".tsx": true, ".mjs": true, ".cjs": true,
		// Python
		".py": true, ".pyx": true, ".pxd": true,
		// Rust
		".rs": true,
		// C/C++
		".c": true, ".h": true, ".cpp": true, ".hpp": true, ".cc": true, ".cxx": true,
		// Java/Kotlin
		".java": true, ".kt": true, ".kts": true,
		// C#
		".cs": true,
		// Ruby
		".rb": true,
		// PHP
		".php": true,
		// Swift
		".swift": true,
		// Shell
		".sh": true, ".bash": true, ".zsh": true,
		// Scala
		".scala": true,
		// Elixir/Erlang
		".ex": true, ".exs": true, ".erl": true,
		// Haskell
		".hs": true,
		// Lua
		".lua": true,
		// R
		".r": true,
		// Dart
		".dart": true,
		// Zig
		".zig": true,
	}
	return codeExts[ext]
}
